const DAYS=["monday","tuesday","wednesday","thursday","friday"]; const DAY_LABELS=["Monday","Tuesday","Wednesday","Thursday","Friday"]; const TODAY_IDX=(()=>{const d=new Date().getDay();return d>=1&&d<=5?d-1:-1})();
const SUBJECT_LEGENDS=[{type:"prog",label:"Programming Concepts",color:"var(--cyan)"},{type:"csm",label:"Computer Systems Maintenance",color:"var(--amber)"},{type:"sheq",label:"SHEQ",color:"var(--green)"},{type:"iss",label:"Information System Support",color:"var(--violet)"},{type:"tc",label:"Technical Communication",color:"var(--rose)"},{type:"nass",label:"NASS",color:"var(--lime)"},{type:"sports",label:"Sports",color:"var(--orange)"}];
let activeFilter="all",searchText="";
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
function formatDateLabel(dateValue){if(!dateValue)return"No date set";const d=new Date(`${dateValue}T00:00:00`);return Number.isNaN(d.getTime())?dateValue:d.toLocaleDateString(undefined,{weekday:"short",day:"numeric",month:"short",year:"numeric"})}
function getDaysUntil(dateValue){if(!dateValue)return null;const t=new Date();t.setHours(0,0,0,0);const d=new Date(`${dateValue}T00:00:00`);if(Number.isNaN(d.getTime()))return null;return Math.round((d-t)/86400000)}
function countdownLabel(item){if(item.status==="done")return"";const days=getDaysUntil(item.dateValue);if(days===null)return"";if(days<0)return`<span class="badge badge-overdue">⚠ ${Math.abs(days)} day${Math.abs(days)===1?"":"s"} late</span>`;if(days===0)return`<span class="badge badge-today">⚡ Today</span>`;if(days===1)return`<span class="badge badge-countdown">1 day left</span>`;return`<span class="badge badge-countdown">${days} days left</span>`}
const dueBadge=item=>item.dueLabel?`<span class="badge badge-due">${esc(item.dueLabel)}</span>`:"";
const priorityBadge=(p="normal")=>`<span class="badge badge-priority-${p}">${({normal:"Normal",fasttrack:"Fasttrack",postponed:"Postponed"}[p]||"Normal")}</span>`;
function renderTopContent(){document.getElementById("site-title").textContent=SITE_CONFIG.siteTitle;document.getElementById("site-subtitle").textContent=SITE_CONFIG.siteSubtitle;document.getElementById("term-label").textContent=SITE_CONFIG.termLabel;document.getElementById("week-focus-title").textContent=SITE_CONFIG.weekFocus.title;document.getElementById("week-focus-text").textContent=SITE_CONFIG.weekFocus.text;document.getElementById("source-note").textContent=SITE_CONFIG.infoSourceNote;document.getElementById("last-updated").textContent=SITE_CONFIG.lastUpdated}
function renderStats(){const total=ANNOUNCEMENTS.length,pending=ANNOUNCEMENTS.filter(i=>i.status==="pending").length,completed=ANNOUNCEMENTS.filter(i=>i.status==="done").length,openAssignments=ANNOUNCEMENTS.filter(i=>i.type==="assignment"&&i.status==="pending").length,openTests=ANNOUNCEMENTS.filter(i=>i.type==="test"&&i.status==="pending").length,fasttrack=ANNOUNCEMENTS.filter(i=>i.priority==="fasttrack"&&i.status==="pending").length;document.getElementById("stats").innerHTML=[{label:"Pending",value:pending,note:`${total} total items`},{label:"Completed",value:completed,note:"Faded but still visible"},{label:"Open assignments",value:openAssignments,note:"Still need action"},{label:"Upcoming tests",value:openTests,note:"Prepare in advance"},{label:"Fasttrack",value:fasttrack,note:"Urgent priority items"}].map(c=>`<div class="stat-card"><div class="stat-label">${esc(c.label)}</div><div class="stat-value">${esc(c.value)}</div><div class="stat-note">${esc(c.note)}</div></div>`).join("")}
function renderTimetable(){document.getElementById("table-head").innerHTML=`<tr>${['<th>Time</th>',...DAY_LABELS.map((l,i)=>`<th class="${i===TODAY_IDX?'today-col':''}">${esc(l)}${i===TODAY_IDX?' ●':''}</th>`)].join('')}</tr>`;if(TODAY_IDX>=0)document.getElementById("today-indicator").innerHTML=`<span class="today-pill">Today: ${DAY_LABELS[TODAY_IDX]}</span>`;document.getElementById("schedule-body").innerHTML=TIMETABLE_DATA.map(slot=>`<tr><td class="time-cell">${esc(slot.time)}</td>${DAYS.map((day,i)=>{const cell=slot[day],td=i===TODAY_IDX?' class="today-col"':'';if(cell.breakLabel){const cls=cell.breakLabel==="LUNCH"?"lunch":"tea",icon=cell.breakLabel==="LUNCH"?"🍽":"☕";return`<td${td}><div class="break-cell"><span class="break-label ${cls}">${icon} ${esc(cell.breakLabel)}</span></div></td>`}const isEmpty=!cell.subject||cell.subject==="No class listed",typeClass=isEmpty?"subject-empty":`subject-${cell.type||''}`;return`<td${td}><div class="subject-card ${typeClass}"><div class="subject-name">${esc(cell.subject||'—')}</div>${cell.lecturer&&!isEmpty?`<div class="subject-lecturer">${esc(cell.lecturer)}</div>`:''}</div></td>`}).join('')}</tr>`).join('');document.getElementById("legend").innerHTML=SUBJECT_LEGENDS.map(i=>`<div class="legend-item"><span class="legend-dot" style="background:${i.color}"></span>${esc(i.label)}</div>`).join('')}
function getFilteredAnnouncements(){return [...ANNOUNCEMENTS].sort((a,b)=>{if(a.pinned!==b.pinned)return a.pinned?-1:1;if(a.status!==b.status)return a.status==="pending"?-1:1;const rank={fasttrack:0,normal:1,postponed:2};if(rank[a.priority||'normal']!==rank[b.priority||'normal'])return rank[a.priority||'normal']-rank[b.priority||'normal'];return(a.dateValue||'').localeCompare(b.dateValue||'')}).filter(item=>{const typeMatch=activeFilter==="all"?true:activeFilter==="open"?item.status==="pending":item.type===activeFilter;const hay=[item.title,item.description,item.type,item.dueLabel,item.source,item.detail,...(item.questions||[]),...(item.actions||[])].join(' ').toLowerCase();return typeMatch&&hay.includes(searchText.toLowerCase())})}
function renderAnnouncements(){const items=getFilteredAnnouncements();if(!items.length){document.getElementById('updates').innerHTML='<div class="empty-state">No items match the current filter.</div>';return}document.getElementById('updates').innerHTML=items.map(item=>`<article class="ann-card type-${esc(item.type)} status-${esc(item.status)}${item.pinned?' pinned-card':''}"><div class="ann-header"><div class="ann-title">${esc(item.title)}</div><div class="badge-row"><span class="badge badge-${esc(item.type)}">${esc(item.type.charAt(0).toUpperCase()+item.type.slice(1))}</span><span class="badge badge-${esc(item.status)}">${item.status==='done'?'✓ Done':'Pending'}</span>${item.pinned?'<span class="badge badge-pinned">📌 Pinned</span>':''}${priorityBadge(item.priority)}${dueBadge(item)}${countdownLabel(item)}</div></div><p class="ann-desc">${esc(item.description)}</p><div class="card-actions"><button class="action-btn" data-open-id="${esc(item.id)}">View details</button></div><div class="ann-footer"><span class="ann-meta">Source: ${esc(item.source)}</span><span class="ann-meta">Updated: ${esc(item.updatedAt)}</span><span class="ann-meta">Date: ${esc(formatDateLabel(item.dateValue))}</span></div></article>`).join('');document.querySelectorAll('[data-open-id]').forEach(b=>b.addEventListener('click',()=>openAnnouncement(b.dataset.openId)))}
function listBlock(title,vals){if(!vals||!vals.length)return'';return`<div class="detail-block"><h3>${esc(title)}</h3><ul>${vals.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></div>`}
function openAnnouncement(id){const item=ANNOUNCEMENTS.find(e=>e.id===id);if(!item)return;document.getElementById('modal-title').textContent=item.title;document.getElementById('modal-sub').textContent=item.description;document.getElementById('modal-content').innerHTML=`<div class="meta-grid"><div class="meta-card"><small>Type</small><strong>${esc(item.type)}</strong></div><div class="meta-card"><small>Status</small><strong>${esc(item.status)}</strong></div><div class="meta-card"><small>Priority</small><strong>${esc(item.priority||'normal')}</strong></div><div class="meta-card"><small>Due</small><strong>${esc(item.dueLabel||'No due label')} · ${esc(formatDateLabel(item.dateValue))}</strong></div><div class="meta-card"><small>Source</small><strong>${esc(item.source)}</strong></div><div class="meta-card"><small>Updated</small><strong>${esc(item.updatedAt)}</strong></div></div><div class="detail-block"><h3>Full details</h3><p>${esc(item.detail||'No full detail added yet.')}</p></div>${listBlock('Questions / prompts',item.questions)}${listBlock('Action checklist',item.actions)}`;document.getElementById('announcement-modal').showModal()}
function bindControls(){document.querySelectorAll('.filter-btn').forEach(button=>button.addEventListener('click',()=>{activeFilter=button.dataset.filter;document.querySelectorAll('.filter-btn').forEach(btn=>btn.classList.remove('active'));button.classList.add('active');renderAnnouncements()}));document.getElementById('search').addEventListener('input',e=>{searchText=e.target.value;renderAnnouncements()});const modal=document.getElementById('announcement-modal');document.getElementById('close-modal').addEventListener('click',()=>modal.close());modal.addEventListener('click',e=>{const r=modal.getBoundingClientRect();const inside=r.top<=e.clientY&&e.clientY<=r.top+r.height&&r.left<=e.clientX&&e.clientX<=r.left+r.width;if(!inside)modal.close()})}
document.addEventListener('DOMContentLoaded',()=>{renderTopContent();renderStats();renderTimetable();renderAnnouncements();bindControls()});
