const SITE_CONFIG = {
  siteTitle: "NC IT Notice Board",
  siteSubtitle: "our class — timetable, assignments, tests, and notices all in one place.",
  termLabel: "NC IT · First Semester · Notice Board",
  lastUpdated: "2026-04-16 08:00",
  infoSourceNote: "I only post what has been confirmed by the lecturer, class rep, timetable, or official class message.",
  weekFocus: { title: "This week's focus", text: "Friday is heavy: Technical Communication print work, Programming case study, Technical Communication test, and Programming test are all active. Keep urgent items pinned and set fasttrack on anything that suddenly becomes more important." }
};
const TIMETABLE_DATA = [
  { time: "08:00 – 10:00", monday:{subject:"SHEQ",lecturer:"B. Ncube",type:"sheq"}, tuesday:{subject:"Computer Systems Maintenance",lecturer:"T. Sithole",type:"csm"}, wednesday:{subject:"NASS",lecturer:"Adult",type:"nass"}, thursday:{subject:"Programming Concepts",lecturer:"S. Mutukwana",type:"prog"}, friday:{subject:"Information System Support",lecturer:"S. Mutukwana",type:"iss"} },
  { time: "10:00 – 10:30", monday:{breakLabel:"BREAK"}, tuesday:{breakLabel:"BREAK"}, wednesday:{breakLabel:"BREAK"}, thursday:{breakLabel:"BREAK"}, friday:{breakLabel:"BREAK"} },
  { time: "10:30 – 12:30", monday:{subject:"Computer Systems Maintenance",lecturer:"T. Sithole",type:"csm"}, tuesday:{subject:"Programming Concepts",lecturer:"B. Mateza",type:"prog"}, wednesday:{subject:"Information System Support",lecturer:"T. Sithole",type:"iss"}, thursday:{subject:"Programming Concepts",lecturer:"B. Mateza",type:"prog"}, friday:{subject:"Technical Communication",lecturer:"V. Shoko",type:"tc"} },
  { time: "12:30 – 14:00", monday:{breakLabel:"LUNCH"}, tuesday:{breakLabel:"LUNCH"}, wednesday:{breakLabel:"LUNCH"}, thursday:{breakLabel:"LUNCH"}, friday:{breakLabel:"LUNCH"} },
  { time: "14:00 – 16:00", monday:{subject:"Programming Concepts",lecturer:"S. Mutukwana",type:"prog"}, tuesday:{subject:"Computer Systems Maintenance",lecturer:"S. Ndawi",type:"csm"}, wednesday:{subject:"Sports",lecturer:"Scheduled activity",type:"sports"}, thursday:{subject:"Information System Support",lecturer:"T. Sithole",type:"iss"}, friday:{subject:"No class listed",lecturer:"—",type:"empty"} }
];
const ANNOUNCEMENTS = [
  { id:"tc-group-print", title:"Print Technical Communication group work", type:"assignment", dueLabel:"Due Friday", dateValue:"2026-04-17", status:"pending", pinned:true, priority:"fasttrack", description:"Technical Communication group work needs to be printed and submitted by Friday.", detail:"Make sure the final group copy is clean, complete, and ready for printing. Confirm page order and group member names before submission.", questions:["Does the printed group work include all required sections?","Have all group members checked the final copy?","Has the cover page or title page been added if required?"], actions:["Finalize the typed version","Print the document","Bring it for submission on Friday"], source:"Class update", updatedAt:"2026-04-15 19:17" },
  { id:"tc-second-task", title:"Second Technical Communication task and print", type:"assignment", dueLabel:"Due Friday", dateValue:"2026-04-17", status:"pending", pinned:false, priority:"normal", description:"Second Technical Communication task also needs to be printed before submission.", detail:"Treat this as a separate task from the group work. Keep the correct title and required formatting before printing.", questions:[], actions:["Confirm the exact task title","Complete the write-up","Print before Friday"], source:"Class update", updatedAt:"2026-04-15 19:17" },
  { id:"csm-case-study", title:"CSM case study", type:"assignment", dueLabel:"Due Thursday", dateValue:"2026-04-16", status:"pending", pinned:true, priority:"fasttrack", description:"Computer Systems Management case study is still outstanding.", detail:"This case study can be opened and read in full from the website. Use the View details button to show the full prompt, questions, and action checklist.", questions:["Identify the main problem in the case study.","List the hardware, software, or maintenance issues mentioned.","Explain the best corrective action for each issue.","State any preventive maintenance practices that would avoid the problem in future."], actions:["Read the full case","Answer each question clearly","Check if it must be printed or submitted by hand"], source:"Ashley / class group", updatedAt:"2026-04-15 19:17" },
  { id:"sheq-homework-test", title:"SHEQ homework test", type:"assignment", dueLabel:"Due Wednesday", dateValue:"2026-04-15", status:"done", pinned:false, priority:"normal", description:"This one is already completed.", detail:"Marked as done. It stays visible for history, but it fades so classmates know it has already been handled.", questions:[], actions:[], source:"Ashley / class group", updatedAt:"2026-04-15 19:17" },
  { id:"programming-case-study", title:"Programming case study", type:"assignment", dueLabel:"Due Friday", dateValue:"2026-04-17", status:"pending", pinned:true, priority:"normal", description:"Programming case study still needs to be completed before Friday.", detail:"Use the modal to store the full question set, code prompts, or answer instructions for classmates.", questions:["Read the programming scenario carefully.","Identify inputs, processing, and outputs.","Write the algorithm or pseudocode.","Convert the logic into C++ or the required programming format."], actions:["Read all requirements","Prepare the answer","Review the logic before submission"], source:"Class update", updatedAt:"2026-04-15 19:17" },
  { id:"csm-test", title:"CSM test", type:"test", dueLabel:"Tuesday", dateValue:"2026-04-14", status:"done", pinned:false, priority:"normal", description:"CSM test already written.", detail:"Completed test item. Leave it in the data if you want a weekly record.", questions:[], actions:[], source:"Tests schedule", updatedAt:"2026-04-15 19:17" },
  { id:"iss-test", title:"ISS test", type:"test", dueLabel:"Wednesday", dateValue:"2026-04-15", status:"done", pinned:false, priority:"normal", description:"Information Systems Support test already completed.", detail:"Completed test item.", questions:[], actions:[], source:"Tests schedule", updatedAt:"2026-04-15 19:17" },
  { id:"tech-communication-test", title:"Technical Communication test", type:"test", dueLabel:"Friday", dateValue:"2026-04-17", status:"pending", pinned:true, priority:"fasttrack", description:"Prepare for the Friday Technical Communication test.", detail:"Use the detail view to store any revision focus areas, chapter list, or lecturer note for the class.", questions:["Which topics are likely to be tested?","Do we need printed notes or only revision?","Are there any instructions from the lecturer?"], actions:["Revise the test topics","Confirm venue and time","Prepare writing materials"], source:"Tests schedule", updatedAt:"2026-04-15 19:17" },
  { id:"programming-test", title:"Programming test", type:"test", dueLabel:"Friday", dateValue:"2026-04-17", status:"pending", pinned:true, priority:"normal", description:"Programming test is scheduled for Friday.", detail:"Put the test coverage, possible exercise style, or preparation instructions here.", questions:["Revise syntax, loops, conditions, and functions.","Practice simple C++ code tracing.","Review input, processing, output flow."], actions:["Revise notes","Practice examples","Prepare for Friday"], source:"Tests schedule", updatedAt:"2026-04-15 19:17" },
  { id:"general-announcements", title:"General announcements area", type:"notice", dueLabel:"Ongoing", dateValue:"2026-04-15", status:"pending", pinned:false, priority:"postponed", description:"Use this section for room changes, urgent lecturer messages, extra classes, or anything the class should know this week.", detail:"This is the flexible notice section. Add last-minute changes here, then pin them if they become urgent.", questions:[], actions:["Keep notices short and confirmed","Add source and updated time","Pin only high-importance notices"], source:"Manual website update", updatedAt:"2026-04-15 19:46" }
];
